version: "3.9"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_HOST_AUTH_METHOD: trust
  redis:
    image: redis:6.2.6
    ports:
      - "6379:6379"
  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/myapp
    depends_on:
      - db
      - redis
  web:
    build:
      context: .
      args:
        BUNDLE_GEMS__CONTRIBSYS__COM: $BUNDLE_GEMS__CONTRIBSYS__COM
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/credishop:cached
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
